In [1]:
import pandas as pd
import random

# Listes de valeurs possibles
suggestions = ["Data Ingenieur", "Data Engineer", "Data Analyst", "Data Analyste", "Data Scientist"]
departements = ["France", "Ain", "Aisne", "Allier", "Alpes-de-Haute-Provence", "Hauts-de-Seine", "Seine-Saint-Denis", "Val-de-Marne", "Val-d'Oise"]
niveau_experience = ["Junior", "Intermédiaire", "Senior"]
secteur_d_activite = ["Tech", "Finance", "Industrie", "Santé", "Marketing", "Autre"]
taille_entreprise = ["Startup", "PME", "Grande entreprise"]
type_de_contrat = ["CDI", "CDD", "Freelance", "Stage", "Alternance"]
teletravail = ["Total", "Partiel", "Aucun"]

# Générer 200 lignes de données fictives
data = {
    "suggestion": [random.choice(suggestions) for _ in range(200)],
    "departement": [random.choice(departements) for _ in range(200)],
    "niveau_experience": [random.choice(niveau_experience) for _ in range(200)],
    "secteur_d_activite": [random.choice(secteur_d_activite) for _ in range(200)],
    "taille_entreprise": [random.choice(taille_entreprise) for _ in range(200)],
    "type_de_contrat": [random.choice(type_de_contrat) for _ in range(200)],
    "teletravail": [random.choice(teletravail) for _ in range(200)],
    "salaire": [random.randint(30000, 100000) for _ in range(200)]
}

# Création du DataFrame
df = pd.DataFrame(data)

# Affichage des premières lignes
df.head()

,suggestion,departement,niveau_experience,secteur_d_activite,taille_entreprise,type_de_contrat,teletravail,salaire
0,Data Ingenieur,Alpes-de-Haute-Provence,Intermédiaire,Industrie,PME,CDI,Total,78429
1,Data Analyst,Ain,Intermédiaire,Finance,PME,CDD,Total,93390
2,Data Analyste,Alpes-de-Haute-Provence,Senior,Santé,PME,Stage,Aucun,73403
3,Data Analyste,Val-d'Oise,Senior,Finance,PME,CDD,Total,50906
4,Data Ingenieur,Aisne,Intermédiaire,Santé,Startup,CDI,Aucun,52703

In [2]:
df.to_csv("df_offres.csv")